os:
  - linux
  - osx
language: ruby
sudo: required
cache: bundler
env:
  os:
    - linux: USE_ATLAS=1 # This configuration installs ATLAS, builds and tests the nmatrix, nmatrix-atlas, and nmatrix-lapacke gems
    - osx: USE_REF=1
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
before_install: ./travis.sh before_install
script: ./travis.sh script

# Define extra configurations to add to the build matrix.
# The idea here is that the USE_ATLAS=1 option should exercise all the ruby
# code, so it is the only one we need to test with all versions of ruby.
# For other configurations we only test with one version of ruby.
matrix:
  include:
    #For some reason this OpenBLAS configuration isn't working on travis, disable it for now.
    #- rvm: 2.2
    #  env: USE_OPENBLAS=1 # Installs OpenBLAS and reference LAPACK, builds and tests nmatrix, nmatrix-lapacke
    - rvm: 2.2
      env: USE_REF=1 # Installs reference implementations of LAPACK and BLAS, builds and tests nmatrix, nmatrix-lapacke
    - rvm: 2.2
      env: NO_EXTERNAL_LIB=1 # No external libraries installed, only nmatrix
  allow_failures:
    - os: osx
notifications:
  irc: "chat.freenode.net#sciruby"
